apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1h 
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
      - mountPath: "/mongo"
        name: mongopvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: mongopvc
      persistentVolumeClaim:
        claimName: mongodb-pvc
status: {}
